version: 2

jobs:
    'python-3.6': 
        docker:
            - image: circleci/python:3.6-stretch-node-browsers
              environment:
                  PYTHON_VERSION: py36
                  PERCY_ENABLE: 0



        steps:
            - checkout

            - run:
                  name: Create virtual env
                  command: python -m venv || virtualenv venv

            - run:
                  name: Write job name
                  command: echo $CIRCLE_JOB > circlejob.txt

            - restore_cache:
                  key: deps1-{{ .Branch }}-{{ checksum "requirements/package.txt" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}

            - run:
                  name: Install dependencies
                  command: |
                      sudo pip install virtualenv --upgrade
                      . venv/bin/activate
                      pip install -r requirements/package.txt
                      npm install --ignore-scripts

            - save_cache:
                  key: deps1-{{ .Branch }}-{{ checksum "requirements/package.txt" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}
                  paths:
                      - 'venv'
                      - 'node_modules'


            - run:
                  name: Build
                  command: |
                      . venv/bin/activate
                      npm run build:js
                      npm run build:py
                      python3 setup.py develop

            - run:
                  name: Run tests
                  command: |
                      . venv/bin/activate
                      pytest dash_canvas
            
            - run:
                  name: Run usage tests
                  command: |
                      . venv/bin/activate
                      pip install -r tests/requirements.txt
                      pytest --driver chrome tests




workflows:
    version: 2
    build:
        jobs:
            - 'python-3.6'
